### ISSUE TITLE
代码质量问题

### ISSUE THREAD

**Issue by QwertyJack** [tjfoc/hyperledger-fabric-gm#2]
简单说说我遇到的问题

* https://github.com/tjfoc/hyperledger-fabric-gm/blob/66bf92f471185f8805d8dad680c00b863d5cd512/orderer/main.go#L62

* `/peer/` 有几个空文件

**Comment by tjfoc** [comment]
已解决（674dcce）

**Comment by QwertyJack** [comment]
Where is IT ?
